version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule: { interval: weekly }
    groups: { frontend: { patterns: ["*"] } }
    open-pull-requests-limit: 10
    labels: ["dependencies", "frontend"]
    commit-message: { prefix: "build(deps)" }
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
    groups: { actions: { patterns: ["*"] } }
    open-pull-requests-limit: 10
    labels: ["dependencies", "github-actions"]
    commit-message: { prefix: "build(deps)" }
  - package-ecosystem: docker
    directory: /
    schedule: { interval: weekly }
    open-pull-requests-limit: 10
    labels: ["dependencies", "docker"]
    commit-message: { prefix: "build(deps)" }
