name: Enforce Action Pinning
on:
  push: { branches: [main], paths: [".github/workflows/**", ".github/actions/**"] }
  pull_request: { paths: [".github/workflows/**", ".github/actions/**"] }
  workflow_dispatch:
permissions: { contents: read }
jobs:
  check:
    uses: nabhold/shared/.github/workflows/enforce-action-pinning.yml@c0b1dfcb5049f4e994e926a6f1ea9ff2b4a02b6c # v1.3.0
