name: Enforce Dependabot Config
on:
  push: { branches: [main], paths: [".github/dependabot.yml"] }
  pull_request: { paths: [".github/dependabot.yml"] }
  workflow_dispatch:
permissions: { contents: read }
jobs:
  check:
    uses: nabhold/shared/.github/workflows/enforce-dependabot-config.yml@c0b1dfcb5049f4e994e926a6f1ea9ff2b4a02b6c # v1.3.0
